PREFIX ex-intent: <https://data.example.com/intent/> 
PREFIX ex-goal: <https://data.example.com/goal/> 
PREFIX ex-action-effect: <https://data.example.com/actionEffect/> 
PREFIX : <https://alex-randles.github.io/Prometheus-Metric-Ontology/>  

SELECT ?goal ?action
WHERE { 
	ex-intent:0 a :Intent;
            :hasGoal ?goal .
    ?goal :isMaintainedBy ?action . 
}
